"""add column slug in table produts

Revision ID: 0c92460b0c10
Revises: 60572d011a74
Create Date: 2024-02-13 19:00:24.574085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c92460b0c10'
down_revision: Union[str, None] = '60572d011a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'slug')
    # ### end Alembic commands ###
