"""alter columns categort_attribute

Revision ID: 60572d011a74
Revises: 
Create Date: 2024-02-13 14:37:24.476088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60572d011a74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_attributes', sa.Column('is_searchable', sa.Boolean(), nullable=True))
    op.add_column('category_attributes', sa.Column('is_show', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_attributes', 'is_show')
    op.drop_column('category_attributes', 'is_searchable')
    # ### end Alembic commands ###
