
# workers
from .workers_handlers.category_versus import category_versus_handler
from .workers_handlers.product_versus import product_versus_handler
from .workers_handlers.detail_product_versus import detail_product_versus_handler
